name: 07 Passing data between steps

on: 
    workflow_dispatch:

jobs: 
    data-sender:
        runs-on: ubuntu-latest

        steps:
            - name: Create data
              id: data-sender
              
              run: |
                echo "name = ayush" >> $GITHUB_OUTPUT
        
        outputs:
            name: ${{steps.data-sender.outputs.name}}

    data-receiver:
        runs-on: ubuntu-latest
        needs: ["data-sender"]

        steps:
            - name: Receive data

              run: |
                echo "Name is ${{needs.data-sender.outputs.name}}"


