name : "Hello World"

on: 
    workflow_dispatch:

jobs:
    Say_Hello_job:
        runs-on: ubuntu-latest
        steps:
            - name: SayHello
              run: echo "Hi Hello How are you?"


         

